services:
  agent:
    image: your-docker-org/agent_app:latest
    container_name: remote-garden-agent
    restart: unless-stopped
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    networks:
      - garden-net
