"""empty message

Revision ID: b6b96dc9989f
Revises: f00f23ad780b
Create Date: 2025-05-14 14:23:34.713443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6b96dc9989f'
down_revision: Union[str, None] = 'f00f23ad780b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gardens', sa.Column('send_notifications', sa.Boolean(), nullable=False))
    op.add_column('gardens', sa.Column('enable_automation', sa.Boolean(), nullable=False))
    op.add_column('gardens', sa.Column('use_fahrenheit', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gardens', 'use_fahrenheit')
    op.drop_column('gardens', 'enable_automation')
    op.drop_column('gardens', 'send_notifications')
    # ### end Alembic commands ###
