"""empty message

Revision ID: b94b1d12d669
Revises: 
Create Date: 2025-05-11 14:00:59.237464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94b1d12d669'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))
    op.add_column('notifications', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("now()")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('notifications', 'updated_at')
    op.drop_column('notifications', 'created_at')
    # ### end Alembic commands ###
