services:
  app:
    build: .
    container_name: remote-garden-api
    restart: unless-stopped
    environment:
      PYTHONPATH: /app
      DB_CONNECTION_STRING: "postgresql+asyncpg://user:password@db:5432/garden"
      HASH_SALT: "s0m3S3cr3tSalt"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: remote-garden-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: garden
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

  redis:
    image: redis:6.2-alpine
    container_name: remote-garden-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  admin-panel:
    build:
      context: .
      dockerfile: admin_app/Dockerfile
    container_name: remote-garden-api-admin-panel
    ports:
      - "8001:8001"
    depends_on:
      - db
    volumes:
      - ./admin_app:/admin_app
      - ./app:/admin_app/app
    environment:
      DB_CONNECTION_STRING: "postgresql+asyncpg://user:password@db:5432/garden"

  migration:
    build:
      context: .
      dockerfile: Dockerfile.migration
    container_name: remote-garden-migration
    depends_on:
      - db
    volumes:
      - ./app:/app
    environment:
      DB_CONNECTION_STRING: "postgresql+psycopg2://user:password@db:5432/garden"
    entrypoint: ["./migration_manager.sh"]
    command: ["-c", "sleep infinity"]
    profiles:
      - manual



volumes:
  postgres_data:
