FROM python:3.11-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv pip install --system .

COPY app/ ./app

RUN chmod +x ./app/utils/migration_manager.sh

ENTRYPOINT ["./app/utils/migration_manager.sh"]
