"""empty message

Revision ID: 01df2f8f9c4f
Revises: b59f9d8202c4
Create Date: 2025-05-24 10:34:42.678872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01df2f8f9c4f"
down_revision: Union[str, None] = "b59f9d8202c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_sub", sa.String(), nullable=True))
    op.create_unique_constraint(None, "users", ["google_sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "google_sub")
    # ### end Alembic commands ###
