from enum import Enum


class DeviceType(str, Enum):
    SOIL_SENSOR = "SOIL_SENSOR"
    LIGHT = "LIGHT"
    TEMPERATURE = "TEMPERATURE"
    CO2 = "CO2"
    ROOF = "ROOF"
    WATER_PUMP = "WATER_PUMP"
    HEATER = "HEATER"
    OTHER = "OTHER"
    FAN = "FAN"
    ATOMIZER = "ATOMIZER"
    HEATING_MAT = "HEATING_MAT"


class NotificationType(str, Enum):
    alert = "alert"
    reminder = "reminder"
    system = "system"


class ScheduleActionType(str, Enum):
    TURN_ON = "TURN_ON"
    TURN_OFF = "TURN_OFF"
    START_WATERING = "START_WATERING"
    OPEN_ROOF = "OPEN_ROOF"
    CLOSE_ROOF = "CLOSE_ROOF"
    INCREASE_TEMPERATURE = "INCREASE_TEMPERATURE"
    DECREASE_TEMPERATURE = "DECREASE_TEMPERATURE"


class ControlActionType(str, Enum):
    TURN_ON = "TURN_ON"
    TURN_OFF = "TURN_OFF"
    START_WATERING = "START_WATERING"
    OPEN_ROOF = "OPEN_ROOF"
    CLOSE_ROOF = "CLOSE_ROOF"
    INCREASE_TEMPERATURE = "INCREASE_TEMPERATURE"
    DECREASE_TEMPERATURE = "DECREASE_TEMPERATURE"
    RESET_ESP = "RESET_ESP"
    WATER_ON = "WATER_ON"
    WATER_OFF = "WATER_OFF"
    ATOMIZE_ON = "ATOMIZE_ON"
    ATOMIZE_OFF = "ATOMIZE_OFF"
    FAN_ON = "FAN_ON"
    FAN_OFF = "FAN_OFF"
    HEATING_MAT_ON = "HEATING_MAT_ON"
    HEATING_MAT_OFF = "HEATING_MAT_OFF"
    # PAIR_ESP = "PAIR_ESP"
